services:
    app:
        image: learningcenter
        build:
            context: .
            dockerfile: docker/production/Dockerfile
            target: production
        env_file:
            - .env.production
        labels:
            # Orbstack expects bare hostnames, not URLs with scheme
            - dev.orbstack.domains=app.learningcenter.orb.local
        ports:
            - "80:80"
            - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
        volumes:
            - ./:${WORKDIR}
            - ./vendor/:${WORKDIR}/vendor
        networks:
            - learningcenter_network
        depends_on:
            - redis
            - pgsql

    pgsql:
        image: 'postgres:17-alpine'
        ports:
            - '5432:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'pgsql:/var/lib/postgresql/data'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - 'lara11'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
        networks:
            - learningcenter_network

    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'redis:/data'
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            retries: 3
            timeout: 5s
        networks:
            - learningcenter_network

volumes:
    pgsql:
        driver: local
    redis: 
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '${REDIS_VOLUME_LOCAL:-./database/redis-database/}'

networks:
    learningcenter_network:
        driver: bridge
