services:
    app:
        image: laravel-app
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - '80:80'
        volumes:
            - '.:/app'
        depends_on:
            - redis

    worker:
      image: laravel-app
      volumes:
        - ".:/app"
      working_dir: /app
      command: "frankenphp php-cli artisan queue:work"
      depends_on: 
        - redis
    
    horizon:
      image: laravel-app
      volumes:
        - ".:/app"
      working_dir: /app
      command: "frankenphp php-cli artisan horizon"
      # Horizon allows for a working healthcheck, so let's add one
      healthcheck:
        test: ["CMD", "frankenphp", "php-cli", "artisan", "horizon:status"]
        timeout: 10s
        retries: 3    
      depends_on: 
        - redis

    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'redis:/data'
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            retries: 3
            timeout: 5s
volumes:
    redis: