#!/bin/bash

# Learning Center Backup Automation Setup
# Sets up automated backup scheduling and monitoring

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BACKUP_CONFIG_FILE="$PROJECT_ROOT/docker/production/backup-config.env"
SYSTEMD_SERVICE_DIR="/etc/systemd/system"
CRON_DIR="/etc/cron.d"
LOG_DIR="/var/log/learning-center"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging
log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

# Load backup configuration
load_config() {
    if [[ -f "$BACKUP_CONFIG_FILE" ]]; then
        source "$BACKUP_CONFIG_FILE"
        log_success "Loaded backup configuration from $BACKUP_CONFIG_FILE"
    else
        log_error "Backup configuration file not found: $BACKUP_CONFIG_FILE"
        exit 1
    fi
}

# Create systemd service for backup system
create_backup_service() {
    log_info "Creating systemd service for backup system..."
    
    cat > "$SYSTEMD_SERVICE_DIR/learning-center-backup.service" << EOF
[Unit]
Description=Learning Center Backup Service
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
User=root
Group=root
WorkingDirectory=$PROJECT_ROOT
EnvironmentFile=$BACKUP_CONFIG_FILE
ExecStart=$SCRIPT_DIR/backup-system.sh backup full
StandardOutput=journal
StandardError=journal
SyslogIdentifier=learning-center-backup

# Security settings
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ReadWritePaths=$BACKUP_BASE_DIR $LOG_DIR /tmp
ProtectHome=true

# Resource limits
CPUQuota=50%
MemoryLimit=1G
IOWeight=100

[Install]
WantedBy=multi-user.target
EOF

    # Create timer for scheduled backups
    cat > "$SYSTEMD_SERVICE_DIR/learning-center-backup.timer" << EOF
[Unit]
Description=Learning Center Backup Timer
Requires=learning-center-backup.service

[Timer]
OnCalendar=daily
Persistent=true
RandomizedDelaySec=300

[Install]
WantedBy=timers.target
EOF

    # Create database backup service
    cat > "$SYSTEMD_SERVICE_DIR/learning-center-db-backup.service" << EOF
[Unit]
Description=Learning Center Database Backup Service
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
User=root
Group=root
WorkingDirectory=$PROJECT_ROOT
EnvironmentFile=$BACKUP_CONFIG_FILE
ExecStart=$SCRIPT_DIR/backup-system.sh backup database
StandardOutput=journal
StandardError=journal
SyslogIdentifier=learning-center-db-backup

# Security settings
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ReadWritePaths=$BACKUP_BASE_DIR $LOG_DIR /tmp
ProtectHome=true

[Install]
WantedBy=multi-user.target
EOF

    # Create timer for database backups
    cat > "$SYSTEMD_SERVICE_DIR/learning-center-db-backup.timer" << EOF
[Unit]
Description=Learning Center Database Backup Timer
Requires=learning-center-db-backup.service

[Timer]
OnCalendar=*-*-* 02,08,14,20:00:00
Persistent=true
RandomizedDelaySec=60

[Install]
WantedBy=timers.target
EOF

    log_success "Created systemd services and timers"
}

# Create cron jobs for backup scheduling
create_cron_jobs() {
    log_info "Creating cron jobs for backup scheduling..."
    
    cat > "$CRON_DIR/learning-center-backup" << EOF
# Learning Center Backup Cron Jobs
# Generated by setup-backup-automation.sh

# Load environment variables
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Full backup - Weekly on Sunday at 2 AM
0 2 * * 0 root cd $PROJECT_ROOT && $SCRIPT_DIR/backup-system.sh backup full >> $LOG_DIR/backup-cron.log 2>&1

# Database backup - Every 6 hours
0 */6 * * * root cd $PROJECT_ROOT && $SCRIPT_DIR/backup-system.sh backup database >> $LOG_DIR/backup-cron.log 2>&1

# Backup cleanup - Daily at 3 AM
0 3 * * * root cd $PROJECT_ROOT && $SCRIPT_DIR/backup-system.sh cleanup >> $LOG_DIR/backup-cron.log 2>&1

# Backup validation - Weekly on Monday at 4 AM
0 4 * * 1 root cd $PROJECT_ROOT && $SCRIPT_DIR/validate-backups.sh >> $LOG_DIR/backup-validation.log 2>&1

# Health check - Every hour
0 * * * * root cd $PROJECT_ROOT && $SCRIPT_DIR/disaster-recovery.sh health >> $LOG_DIR/health-check.log 2>&1
EOF

    chmod 644 "$CRON_DIR/learning-center-backup"
    log_success "Created cron jobs"
}

# Create backup validation script
create_validation_script() {
    log_info "Creating backup validation script..."
    
    cat > "$SCRIPT_DIR/validate-backups.sh" << 'EOF'
#!/bin/bash

# Learning Center Backup Validation Script
# Validates recent backups and reports status

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BACKUP_CONFIG_FILE="$PROJECT_ROOT/docker/production/backup-config.env"

# Load configuration
if [[ -f "$BACKUP_CONFIG_FILE" ]]; then
    source "$BACKUP_CONFIG_FILE"
fi

BACKUP_BASE_DIR="${BACKUP_BASE_DIR:-/var/backups/learning-center}"
VALIDATION_SAMPLE_SIZE="${VALIDATION_SAMPLE_SIZE:-3}"

log_info() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO] $*"; }
log_error() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [ERROR] $*"; }
log_success() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [SUCCESS] $*"; }

# Validate recent backups
validate_recent_backups() {
    log_info "Validating recent backups..."
    
    local backup_count=0
    local validation_failures=0
    
    # Find recent backup manifests
    find "$BACKUP_BASE_DIR" -name "manifest-*.json" | sort -r | head -n "$VALIDATION_SAMPLE_SIZE" | while read -r manifest; do
        backup_count=$((backup_count + 1))
        local backup_id=$(basename "$(dirname "$manifest")")
        
        log_info "Validating backup: $backup_id"
        
        if "$SCRIPT_DIR/backup-system.sh" verify "$backup_id"; then
            log_success "Backup validation passed: $backup_id"
        else
            log_error "Backup validation failed: $backup_id"
            validation_failures=$((validation_failures + 1))
        fi
    done
    
    if [[ $validation_failures -eq 0 ]]; then
        log_success "All backup validations passed ($backup_count backups checked)"
    else
        log_error "$validation_failures out of $backup_count backup validations failed"
        exit 1
    fi
}

# Generate validation report
generate_validation_report() {
    local report_file="/tmp/backup-validation-$(date +%Y%m%d_%H%M%S).json"
    
    cat > "$report_file" << EOF
{
  "validation_date": "$(date -Iseconds)",
  "backup_base_dir": "$BACKUP_BASE_DIR",
  "sample_size": $VALIDATION_SAMPLE_SIZE,
  "total_backups": $(find "$BACKUP_BASE_DIR" -name "manifest-*.json" | wc -l),
  "disk_usage": "$(du -sh "$BACKUP_BASE_DIR" 2>/dev/null | cut -f1 || echo 'Unknown')",
  "oldest_backup": "$(find "$BACKUP_BASE_DIR" -name "manifest-*.json" | sort | head -1 | xargs -I {} jq -r '.backup_date' {} 2>/dev/null || echo 'Unknown')",
  "newest_backup": "$(find "$BACKUP_BASE_DIR" -name "manifest-*.json" | sort -r | head -1 | xargs -I {} jq -r '.backup_date' {} 2>/dev/null || echo 'Unknown')"
}
EOF
    
    log_success "Generated validation report: $report_file"
}

# Main execution
main() {
    validate_recent_backups
    generate_validation_report
}

main "$@"
EOF

    chmod +x "$SCRIPT_DIR/validate-backups.sh"
    log_success "Created backup validation script"
}

# Create monitoring and alerting setup
create_monitoring_setup() {
    log_info "Creating monitoring and alerting setup..."
    
    # Create backup monitoring script
    cat > "$SCRIPT_DIR/backup-monitor.sh" << 'EOF'
#!/bin/bash

# Learning Center Backup Monitoring Script
# Monitors backup processes and sends alerts

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BACKUP_CONFIG_FILE="$PROJECT_ROOT/docker/production/backup-config.env"

# Load configuration
if [[ -f "$BACKUP_CONFIG_FILE" ]]; then
    source "$BACKUP_CONFIG_FILE"
fi

BACKUP_BASE_DIR="${BACKUP_BASE_DIR:-/var/backups/learning-center}"
ALERT_THRESHOLD_HOURS="${ALERT_THRESHOLD_HOURS:-25}" # Alert if no backup in 25 hours

log_info() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO] $*"; }
log_warn() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [WARN] $*"; }
log_error() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [ERROR] $*"; }

# Send alert function
send_alert() {
    local alert_type="$1"
    local message="$2"
    
    # Webhook notification
    if [[ "${WEBHOOK_ENABLED:-false}" == "true" && -n "${WEBHOOK_URL:-}" ]]; then
        curl -s -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "{\"text\":\"🚨 Learning Center Backup Alert: $alert_type\\n$message\"}" \
            || log_warn "Failed to send webhook alert"
    fi
    
    # Email notification
    if [[ "${EMAIL_ALERTS_ENABLED:-false}" == "true" && -n "${ALERT_EMAIL:-}" ]]; then
        echo "$message" | mail -s "Learning Center Backup Alert: $alert_type" "$ALERT_EMAIL" \
            || log_warn "Failed to send email alert"
    fi
}

# Check backup freshness
check_backup_freshness() {
    log_info "Checking backup freshness..."
    
    local latest_backup=$(find "$BACKUP_BASE_DIR" -name "manifest-*.json" | sort -r | head -1)
    
    if [[ -z "$latest_backup" ]]; then
        log_error "No backups found"
        send_alert "NO_BACKUPS" "No backups found in $BACKUP_BASE_DIR"
        return 1
    fi
    
    local backup_time=$(stat -c %Y "$latest_backup")
    local current_time=$(date +%s)
    local age_hours=$(( (current_time - backup_time) / 3600 ))
    
    if [[ $age_hours -gt $ALERT_THRESHOLD_HOURS ]]; then
        log_warn "Latest backup is $age_hours hours old (threshold: $ALERT_THRESHOLD_HOURS hours)"
        send_alert "STALE_BACKUP" "Latest backup is $age_hours hours old. Last backup: $(date -d @$backup_time)"
        return 1
    else
        log_info "Latest backup is $age_hours hours old (within threshold)"
        return 0
    fi
}

# Check disk space
check_disk_space() {
    log_info "Checking backup disk space..."
    
    local disk_usage=$(df "$BACKUP_BASE_DIR" | awk 'NR==2 {print $5}' | sed 's/%//')
    local disk_threshold="${DISK_ALERT_THRESHOLD:-85}"
    
    if [[ $disk_usage -gt $disk_threshold ]]; then
        log_warn "Backup disk usage is ${disk_usage}% (threshold: ${disk_threshold}%)"
        send_alert "DISK_SPACE" "Backup disk usage is ${disk_usage}% on $(hostname)"
        return 1
    else
        log_info "Backup disk usage is ${disk_usage}% (within threshold)"
        return 0
    fi
}

# Check backup processes
check_backup_processes() {
    log_info "Checking backup processes..."
    
    local backup_lock_file="${BACKUP_LOCK_FILE:-/var/run/learning-center-backup.lock}"
    
    if [[ -f "$backup_lock_file" ]]; then
        local lock_age=$(( $(date +%s) - $(stat -c %Y "$backup_lock_file") ))
        local max_backup_time="${MAX_BACKUP_TIME:-14400}" # 4 hours
        
        if [[ $lock_age -gt $max_backup_time ]]; then
            log_error "Backup process appears stuck (lock file age: $lock_age seconds)"
            send_alert "STUCK_BACKUP" "Backup process appears stuck for $lock_age seconds on $(hostname)"
            return 1
        else
            log_info "Backup process is running (lock age: $lock_age seconds)"
        fi
    fi
    
    return 0
}

# Main monitoring function
main() {
    local issues=0
    
    check_backup_freshness || issues=$((issues + 1))
    check_disk_space || issues=$((issues + 1))
    check_backup_processes || issues=$((issues + 1))
    
    if [[ $issues -eq 0 ]]; then
        log_info "All backup monitoring checks passed"
    else
        log_error "$issues backup monitoring issues detected"
        exit 1
    fi
}

main "$@"
EOF

    chmod +x "$SCRIPT_DIR/backup-monitor.sh"
    
    # Add monitoring to cron
    echo "" >> "$CRON_DIR/learning-center-backup"
    echo "# Backup monitoring - Every 2 hours" >> "$CRON_DIR/learning-center-backup"
    echo "0 */2 * * * root cd $PROJECT_ROOT && $SCRIPT_DIR/backup-monitor.sh >> $LOG_DIR/backup-monitor.log 2>&1" >> "$CRON_DIR/learning-center-backup"
    
    log_success "Created backup monitoring setup"
}

# Create log rotation configuration
create_log_rotation() {
    log_info "Creating log rotation configuration..."
    
    cat > "/etc/logrotate.d/learning-center-backup" << EOF
$LOG_DIR/backup*.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    create 644 root root
    postrotate
        systemctl reload rsyslog > /dev/null 2>&1 || true
    endscript
}

$LOG_DIR/health-check.log {
    weekly
    rotate 12
    compress
    delaycompress
    missingok
    notifempty
    create 644 root root
}

$LOG_DIR/backup-monitor.log {
    weekly
    rotate 8
    compress
    delaycompress
    missingok
    notifempty
    create 644 root root
}
EOF

    log_success "Created log rotation configuration"
}

# Setup directories and permissions
setup_directories() {
    log_info "Setting up directories and permissions..."
    
    # Create backup directory
    mkdir -p "$BACKUP_BASE_DIR"/{logs,temp}
    chmod 700 "$BACKUP_BASE_DIR"
    
    # Create log directory
    mkdir -p "$LOG_DIR"
    chmod 755 "$LOG_DIR"
    
    # Create encryption key directory
    mkdir -p /etc/learning-center
    chmod 700 /etc/learning-center
    
    # Generate encryption key if it doesn't exist
    if [[ ! -f /etc/learning-center/backup-encryption.key ]]; then
        openssl rand -base64 32 > /etc/learning-center/backup-encryption.key
        chmod 600 /etc/learning-center/backup-encryption.key
        log_success "Generated backup encryption key"
    fi
    
    log_success "Directories and permissions configured"
}

# Enable and start services
enable_services() {
    log_info "Enabling and starting services..."
    
    # Reload systemd
    systemctl daemon-reload
    
    # Enable and start backup services
    systemctl enable learning-center-backup.timer
    systemctl start learning-center-backup.timer
    
    systemctl enable learning-center-db-backup.timer
    systemctl start learning-center-db-backup.timer
    
    # Restart cron service
    systemctl restart cron
    
    log_success "Services enabled and started"
}

# Test backup system
test_backup_system() {
    log_info "Testing backup system..."
    
    # Test backup script
    if "$SCRIPT_DIR/backup-system.sh" help >/dev/null 2>&1; then
        log_success "Backup script is functional"
    else
        log_error "Backup script test failed"
        return 1
    fi
    
    # Test disaster recovery script
    if "$SCRIPT_DIR/disaster-recovery.sh" help >/dev/null 2>&1; then
        log_success "Disaster recovery script is functional"
    else
        log_error "Disaster recovery script test failed"
        return 1
    fi
    
    # Test validation script
    if "$SCRIPT_DIR/validate-backups.sh" >/dev/null 2>&1 || true; then
        log_success "Validation script is functional"
    else
        log_warn "Validation script test had issues (may be normal if no backups exist)"
    fi
    
    log_success "Backup system tests completed"
}

# Display status and next steps
show_status() {
    log_info "Backup automation setup completed!"
    echo
    echo "Services created:"
    echo "  - learning-center-backup.service (daily full backups)"
    echo "  - learning-center-db-backup.service (6-hourly database backups)"
    echo
    echo "Cron jobs created:"
    echo "  - Full backup: Weekly on Sunday at 2 AM"
    echo "  - Database backup: Every 6 hours"
    echo "  - Cleanup: Daily at 3 AM"
    echo "  - Validation: Weekly on Monday at 4 AM"
    echo "  - Monitoring: Every 2 hours"
    echo
    echo "Configuration file: $BACKUP_CONFIG_FILE"
    echo "Log directory: $LOG_DIR"
    echo "Backup directory: $BACKUP_BASE_DIR"
    echo
    echo "To check service status:"
    echo "  systemctl status learning-center-backup.timer"
    echo "  systemctl status learning-center-db-backup.timer"
    echo
    echo "To run manual backup:"
    echo "  $SCRIPT_DIR/backup-system.sh backup full"
    echo
    echo "To check backup status:"
    echo "  $SCRIPT_DIR/backup-system.sh list"
    echo
    echo "To test disaster recovery:"
    echo "  $SCRIPT_DIR/disaster-recovery.sh health"
}

# Main setup function
main() {
    log_info "Starting Learning Center backup automation setup..."
    
    check_root
    load_config
    setup_directories
    create_backup_service
    create_cron_jobs
    create_validation_script
    create_monitoring_setup
    create_log_rotation
    enable_services
    test_backup_system
    show_status
    
    log_success "Backup automation setup completed successfully!"
}

# Run main function
main "$@"